### ISSUE TITLE
Release on HF?

### ISSUE THREAD

**Issue by vishaal27** [olawalesalaudeen/imagenot#1]
Hey, thanks for the great work, super cool paper!
When you release the dataset, are you planning to release it on HF? Or would it be similar to the LAIONNet style where you release a list of urls and we have to download through img2dataset?
Thanks!

**Comment by olawalesalaudeen** [comment]
Hi Vishaal,

We are not planning to release the dataset. However, the class names are public already; we will release the full code to generate a local facsimile of ImageNot soon. It is a modification of the LAIONNet code though, so you could do it now with their codebase.

Since ImageNot is simply a construction to test the external validity of ImageNet, not a dataset we expect to use outside of that, this is sufficient to reproduce and build on our results. Thanks for your interest!

Regards,

Olawale Salaudeen
________________________________
From: Vishaal Udandarao ***@***.***>
Sent: Wednesday, April 3, 2024 12:29 AM
To: olawalesalaudeen/imagenot ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [olawalesalaudeen/imagenot] Release on HF? (Issue #1)


Hey, thanks for the great work, super cool paper!
When you release the dataset, are you planning to release it on HF? Or would it be similar to the LAIONNet style where you release a list of urls and we have to download through img2dataset?
Thanks!

**Comment by vishaal27** [comment]
Great, thanks!
